apiVersion: "pipeline.shaoxt/v1"
kind: Template
metadata:
  name: java-service
spec:
  templateSpec:
     language: java
     applicationType: service
     sourceControl: Git
     buildTool: Maven
     testTool: JUnit
     packagingTool: Docker
status: Active