apiVersion: "pipeline.shaoxt/v1"
kind: Template
metadata:
  name: java-service
spec:
   language: java
   applicationType: service
   sourceControl: Git
   buildTool: Javac
   testTool: JUnit
   packagingTool: Docker
   stages:
     - Checkout
     - Build
     - Packaging
     - Ship
     - Run
status: Active