// +build !ignore_autogenerated

/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	SchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_Application_To_v1alpha1_Application,
		Convert_v1alpha1_ApplicationList_To_v1alpha1_ApplicationList,
		Convert_v1alpha1_ApplicationSpec_To_v1alpha1_ApplicationSpec,
		Convert_v1alpha1_GitRepo_To_v1alpha1_GitRepo,
		Convert_v1alpha1_Pipeline_To_v1alpha1_Pipeline,
		Convert_v1alpha1_PipelineList_To_v1alpha1_PipelineList,
		Convert_v1alpha1_PipelineSpec_To_v1alpha1_PipelineSpec,
		Convert_v1alpha1_Stack_To_v1alpha1_Stack,
		Convert_v1alpha1_StackList_To_v1alpha1_StackList,
		Convert_v1alpha1_StackSpec_To_v1alpha1_StackSpec,
		Convert_v1alpha1_Status_To_v1alpha1_Status,
	)
}

func autoConvert_v1alpha1_Application_To_v1alpha1_Application(in *Application, out *Application, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1alpha1_Application_To_v1alpha1_Application is an autogenerated conversion function.
func Convert_v1alpha1_Application_To_v1alpha1_Application(in *Application, out *Application, s conversion.Scope) error {
	return autoConvert_v1alpha1_Application_To_v1alpha1_Application(in, out, s)
}


func autoConvert_v1alpha1_ApplicationList_To_v1alpha1_ApplicationList(in *ApplicationList, out *ApplicationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Application)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ApplicationList_To_v1alpha1_ApplicationList is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationList_To_v1alpha1_ApplicationList(in *ApplicationList, out *ApplicationList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationList_To_v1alpha1_ApplicationList(in, out, s)
}

// Convert_v1alpha1_ApplicationSpec_To_v1alpha1_ApplicationSpec is an autogenerated conversion function.
func Convert_v1alpha1_ApplicationSpec_To_v1alpha1_ApplicationSpec(in *ApplicationSpec, out *ApplicationSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_ApplicationSpec_To_v1alpha1_ApplicationSpec(in, out, s)
}

func autoConvert_v1alpha1_ApplicationSpec_To_v1alpha1_ApplicationSpec(in *ApplicationSpec, out *ApplicationSpec, s conversion.Scope) error {
	out.ApplicationId = in.ApplicationId
	out.Stack = in.Stack
	out.GitRepo = in.GitRepo
	out.Owner = in.Owner
	out.VersioningScheme = in.VersioningScheme
	return nil
}

// Convert_v1alpha1_GitRepo_To_v1alpha1_GitRepo is an autogenerated conversion function.
func Convert_v1alpha1_GitRepo_To_v1alpha1_GitRepo(in *GitRepo, out *GitRepo, s conversion.Scope) error {
	return autoConvert_v1alpha1_GitRepo_To_v1alpha1_GitRepo(in, out, s)
}

func autoConvert_v1alpha1_GitRepo_To_v1alpha1_GitRepo(in *GitRepo, out *GitRepo, s conversion.Scope) error {
	out.URL = in.URL
	out.SharedSecret = in.SharedSecret
	return nil
}

func autoConvert_v1alpha1_Pipeline_To_v1alpha1_Pipeline(in *Pipeline, out *Pipeline, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1alpha1_Pipeline_To_v1alpha1_Pipeline is an autogenerated conversion function.
func Convert_v1alpha1_Pipeline_To_v1alpha1_Pipeline(in *Pipeline, out *Pipeline, s conversion.Scope) error {
	return autoConvert_v1alpha1_Pipeline_To_v1alpha1_Pipeline(in, out, s)
}

func autoConvert_v1alpha1_PipelineList_To_v1alpha1_PipelineList(in *PipelineList, out *PipelineList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Pipeline)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_PipelineList_To_v1alpha1_PipelineList is an autogenerated conversion function.
func Convert_v1alpha1_PipelineList_To_v1alpha1_PipelineList(in *PipelineList, out *PipelineList, s conversion.Scope) error {
	return autoConvert_v1alpha1_PipelineList_To_v1alpha1_PipelineList(in, out, s)
}


func autoConvert_v1alpha1_PipelineSpec_To_v1alpha1_PipelineSpec(in *PipelineSpec, out *PipelineSpec, s conversion.Scope) error {
	out.Application = in.Application
	out.Stage = *(*[]StageName)(unsafe.Pointer(&in.Stage))
	out.CurrentStage = StageName(in.CurrentStage)
	out.VersioningScheme = in.VersioningScheme
	return nil
}

// Convert_v1alpha1_PipelineSpec_To_v1alpha1_PipelineSpec is an autogenerated conversion function.
func Convert_v1alpha1_PipelineSpec_To_v1alpha1_PipelineSpec(in *PipelineSpec, out *PipelineSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_PipelineSpec_To_v1alpha1_PipelineSpec(in, out, s)
}

func autoConvert_v1alpha1_Stack_To_v1alpha1_Stack(in *Stack, out *Stack, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Spec = in.Spec
	out.Status = in.Status
	return nil
}

// Convert_v1alpha1_Stack_To_v1alpha1_Stack is an autogenerated conversion function.
func Convert_v1alpha1_Stack_To_v1alpha1_Stack(in *Stack, out *Stack, s conversion.Scope) error {
	return autoConvert_v1alpha1_Stack_To_v1alpha1_Stack(in, out, s)
}

func autoConvert_v1alpha1_StackList_To_v1alpha1_StackList(in *StackList, out *StackList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Stack)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_StackList_To_v1alpha1_StackList is an autogenerated conversion function.
func Convert_v1alpha1_StackList_To_v1alpha1_StackList(in *StackList, out *StackList, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackList_To_v1alpha1_StackList(in, out, s)
}

func autoConvert_v1alpha1_StackSpec_To_v1alpha1_StackSpec(in *StackSpec, out *StackSpec, s conversion.Scope) error {
	out.Language = Language(in.Language)
	out.ApplicationType = ApplicationType(in.ApplicationType)
	out.SourceControl = SourceControl(in.SourceControl)
	out.BuildTool = BuildTool(in.BuildTool)
	out.TestTool = TestTool(in.TestTool)
	out.PackagingTool = PackagingTool(in.PackagingTool)
	out.ImageRepo = ImageRepo(in.ImageRepo)
	out.VersioningScheme = in.VersioningScheme
	return nil
}

// Convert_v1alpha1_StackSpec_To_v1alpha1_StackSpec is an autogenerated conversion function.
func Convert_v1alpha1_StackSpec_To_v1alpha1_StackSpec(in *StackSpec, out *StackSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_StackSpec_To_v1alpha1_StackSpec(in, out, s)
}

func autoConvert_v1alpha1_Status_To_v1alpha1_Status(in *Status, out *Status, s conversion.Scope) error {
	out.Phase = Phase(in.Phase)
	out.StartTime = (*v1.Time)(unsafe.Pointer(in.StartTime))
	return nil
}

// Convert_v1alpha1_Status_To_v1alpha1_Status is an autogenerated conversion function.
func Convert_v1alpha1_Status_To_v1alpha1_Status(in *Status, out *Status, s conversion.Scope) error {
	return autoConvert_v1alpha1_Status_To_v1alpha1_Status(in, out, s)
}